### ISSUE TITLE
 java.lang.IllegalArgumentException: View=DecorView@9319593[] not attached to window manager

### ISSUE THREAD

**Issue by phanvanduc** [imjeevandeshmukh/GlideToast#1]
hi add,
When i show toast, then i start activity then get error
 java.lang.IllegalArgumentException: View=DecorView@9319593[] not attached to window manager
pls help me.
Thanks ad.

**Comment by jeevan-antariksh** [comment]
make sure you window is visible (GlideToast is depended on Activity so make sure while your Intenting other activity animation of GlideToast is complete )
other reason can be your Activity is dead.
